### ISSUE TITLE
gasp

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/no_term#1]
Prof sto facendo gli esercizi di gasp ma ogni volta che lancio il file .py si apre gasp ma non disegna nulla. Questo l'output: 
luigi@luigi-desktop:~/no_term$ python draw.py                                                                     
/usr/lib/python2.7/dist-packages/gasp/backend.py:223: GtkWarning: Impossibile trovare il motore del tema in module_path: «adwaita»,                                                                                                 
  screen.window = gtk.Window()                                                                                    
luigi@luigi-desktop:~/no_term$

**Comment by LuigiVessella** [comment]
Ok ora mi ha disegnato la linea ma da sempre quel messaggio..è normale?

**Comment by FabioZTessitore** [comment]
non hai caricato niente

**Comment by LuigiVessella** [comment]
Si ancora no...volevo prima risolvere questo fatto della libreria

Il 12 feb 2017 20:16, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Ok ho caricato e ho risolto
