### ISSUE TITLE
The sum py

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/no_term#3]
Prova con la versione python

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by LuigiVessella** [comment]
No prof scusatemi ma con tra corso pon, sport e altri impegni non trovo il
tempo...Appena posso mi metto a lavoro

Il 17 feb 2017 17:20, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Prof ho caricato ma da errore sulla conversione in intero..e poi per il salvataggio..lo salvo sempre intero o stringa?

**Comment by FabioZTessitore** [comment]
Pensa, leggi e pensa

**Comment by LuigiVessella** [comment]
Ho risolto il fatto della stringa..Perchè dato che lui restituisce una stringa quando leggiamo, anche quando scriviamo dobbiamo mandare una stringa, giusto?

**Comment by LuigiVessella** [comment]
Fatto...ma non lo crea se non esiste.. Ma nel python ! come si traduce? mi so scordato ahah

**Comment by LuigiVessella** [comment]
Prof ora va bene?
 A me da un errore strano " Non-ASCII character '\xc3' in file thesum.py.."

**Comment by FabioZTessitore** [comment]
Il problema è la lettera accentata.

Cmq fai attenzione, non l'hai fatto allo stesso modo di quello in C
